name: simple_clean_getit_generator
description: Simple getIt generator on clean architecture
homepage: https://github.com/anggaaryas/simple_clean_getit_generator

version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  path: ^1.8.2
  glob: ^2.0.2

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.1.11
  test: ^1.21.1
  source_gen_test: ^1.0.3